[package]
name = "slei-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
axum.workspace = true
chrono = "0.4"
chrono-tz = "0.10"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "webp"] }
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10"
slei-default-agent-assets = { path = "../slei-default-agent-assets" }
slei-protocol = { path = "../slei-protocol" }
slei-storage = { path = "../slei-storage" }
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
tower.workspace = true
