[package]
name = "slei-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
slei-default-agent-assets = { path = "../slei-default-agent-assets" }
slei-protocol = { path = "../slei-protocol" }
slei-storage = { path = "../slei-storage" }
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
tower.workspace = true
