import { describe, expect, it } from "vitest";

import { existsSync, mkdirSync, readFileSync, readlinkSync, realpathSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { mkdtempSync } from "node:fs";

import { prepareWorkspace } from "./overlay.js";
import type { RuntimeSession } from "./protocol.js";

describe("Slei overlay workspace", () => {
  it("creates a reusable project-set overlay independent of mount order", () => {
    const root = mkdtempSync(join(tmpdir(), "slei-overlay-test-"));
    const overlayHome = join(root, "overlays");
    const previousOverlayHome = process.env.SLEI_OVERLAY_HOME;
    process.env.SLEI_OVERLAY_HOME = overlayHome;
    try {
      const agent = makeAgent(root);
      const api = makeProject(root, "API", "review", "Review API changes.");
      const web = makeProject(root, "Web", "deploy", "Deploy web.");
      const first = prepareWorkspace(session(agent, [api, web]));
      const second = prepareWorkspace(session(agent, [web, api]));

      const firstWorkspaceSet = readlinkSync(join(first.cwd, "workspaces"));
      const secondWorkspaceSet = readlinkSync(join(second.cwd, "workspaces"));
      expect(firstWorkspaceSet).toBe(secondWorkspaceSet);
      expect(existsSync(join(first.cwd, ".claude", "skills", "memory"))).toBe(true);
      expect(existsSync(join(first.cwd, ".claude", "skills", "review"))).toBe(true);
      expect(first.runtimeContext).toContain(`Agent workspace: ${realpathSync(agent)}`);
      expect(first.additionalDirectories).toEqual(expect.arrayContaining([realpathSync(agent), realpathSync(api), realpathSync(web)]));
    } finally {
      restoreEnv("SLEI_OVERLAY_HOME", previousOverlayHome);
    }
  });

  it("namespaces same-name skills while keeping agent skills at the natural name", () => {
    const root = mkdtempSync(join(tmpdir(), "slei-overlay-conflict-"));
    const previousOverlayHome = process.env.SLEI_OVERLAY_HOME;
    process.env.SLEI_OVERLAY_HOME = join(root, "overlays");
    try {
      const agent = makeAgent(root);
      const api = makeProject(root, "API", "memory", "Project memory skill.");
      const web = makeProject(root, "Web", "memory", "Web memory skill.");
      const prepared = prepareWorkspace(session(agent, [api, web], api));
      const skillsRoot = join(prepared.cwd, ".claude", "skills");

      expect(readlinkSync(join(skillsRoot, "memory"))).toContain(join(".slei", "agents", "agent_yeal", ".claude", "skills", "memory"));
      expect(readFileSync(join(skillsRoot, "api-memory", "SKILL.md"), "utf8")).toContain("name: api-memory");
      expect(readFileSync(join(skillsRoot, "web-memory", "SKILL.md"), "utf8")).toContain("name: web-memory");
      expect(existsSync(join(skillsRoot, "api-memory", "source"))).toBe(true);
    } finally {
      restoreEnv("SLEI_OVERLAY_HOME", previousOverlayHome);
    }
  });

  it("mounts linked files under files and documents the aggregate workspace", () => {
    const root = mkdtempSync(join(tmpdir(), "slei-overlay-file-"));
    const previousOverlayHome = process.env.SLEI_OVERLAY_HOME;
    process.env.SLEI_OVERLAY_HOME = join(root, "overlays");
    try {
      const agent = makeAgent(root);
      const linkedFile = join(root, "brief.md");
      writeFileSync(linkedFile, "# Brief");
      const prepared = prepareWorkspace(session(agent, [linkedFile]));
      const filesRoot = readlinkSync(join(prepared.cwd, "files"));
      const mountedFile = join(prepared.cwd, "files", "01-brief-md");
      const claude = readFileSync(join(prepared.cwd, "CLAUDE.md"), "utf8");

      expect(filesRoot).toContain("workspace-sets");
      expect(readlinkSync(mountedFile)).toBe(realpathSync(linkedFile));
      expect(claude).toContain("This is a shared project-set overlay generated by Slei.");
      expect(claude).toContain("files/01-brief-md");
    } finally {
      restoreEnv("SLEI_OVERLAY_HOME", previousOverlayHome);
    }
  });
});

function session(agentWorkspacePath: string, paths: string[], primaryProjectPath?: string): RuntimeSession {
  return {
    session_id: "11111111-1111-4111-8111-111111111111",
    agent_id: "agent_yeal",
    runtime: "ClaudeCode",
    cwd: agentWorkspacePath,
    agent_workspace_path: agentWorkspacePath,
    channel_id: "all",
    channel_name: "all",
    primary_project_path: primaryProjectPath,
    workspace_mounts: paths.map((path) => ({ path, label: path.split("/").at(-1) })),
    persist_session: true,
    resume_session: false,
  };
}

function makeAgent(root: string) {
  const agent = join(root, ".slei", "agents", "agent_yeal");
  mkdirSync(join(agent, ".claude", "skills", "memory"), { recursive: true });
  writeFileSync(join(agent, "MEMORY.md"), "# Yeal\n\nGuide memory.");
  writeFileSync(join(agent, ".claude", "skills", "memory", "SKILL.md"), "---\nname: memory\ndescription: Remember things.\n---\n\nUse memory.");
  return agent;
}

function makeProject(root: string, name: string, skillName: string, description: string) {
  const project = join(root, name);
  mkdirSync(join(project, ".claude", "skills", skillName), { recursive: true });
  writeFileSync(join(project, "CLAUDE.md"), `# ${name}`);
  writeFileSync(join(project, ".claude", "skills", skillName, "SKILL.md"), `---\nname: ${skillName}\ndescription: ${description}\n---\n\nUse ${skillName}.`);
  return project;
}

function restoreEnv(name: string, value: string | undefined) {
  if (value === undefined) {
    delete process.env[name];
  } else {
    process.env[name] = value;
  }
}
